'use client'
import type { Metadata } from "next";
import "./globals.css";
import { satoshi } from "@/config/font";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { useEffect, useState } from "react";
import { Icon } from "@iconify/react/dist/iconify.js";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showBackToTop, setShowBackToTop] = useState(false);


  useEffect(() => {
    const handleScroll = () => {
      setShowBackToTop(window.scrollY > 300);
      
      // // Update active section based on scroll position
      // const sections = document.querySelectorAll('section[id]');
      // let current = '';
      
      // sections.forEach((section) => {
      //   const sectionTop = (section as HTMLElement).offsetTop - 100;
      //   if (window.scrollY >= sectionTop) {
      //     current = section.getAttribute('id') || '';
      //   }
      // });
      
      // setActiveSection(current);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${satoshi.variable} antialiased`}
      >
        <div className="relative flex flex-col h-screen">
          <main className="flex-grow">
            <Header/>
            {children}
            <Footer />
              {showBackToTop && (
        <button
          onClick={scrollToTop}
          className="fixed bottom-8 right-8 bg-gradient-to-b from-[#DAA520] to-[#D35400] text-white p-3 rounded-full shadow-lg transition-all duration-300 z-50"
          aria-label="Back to top"
        >
        <Icon icon="line-md:chevron-up" width="24" height="24" />
        </button>
      )}
           </main>
         </div>
      </body>
    </html>
  );
}
