import type { Metadata } from "next";
import "./globals.css";
import { satoshi } from "@/config/font";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${satoshi.variable} antialiased`}
      >
        <div className="relative flex flex-col h-screen">
          <main className="flex-grow">
            <Header/>
            {children}
            <Footer/>
           </main>
         </div>
      </body>
    </html>
  );
}
