'use client'
import type { Metadata } from "next";
import "./globals.css";
import { satoshi } from "@/config/font";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { useEffect, useState } from "react";
import { Icon } from "@iconify/react/dist/iconify.js";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showBackToTop, setShowBackToTop] = useState(false);


  useEffect(() => {
    const handleScroll = () => {
      setShowBackToTop(window.scrollY > 300);
      
      // // Update active section based on scroll posi
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${satoshi.variable} antialiased min-h-screen`}
      >
       {children}
      </body>
    </html>
  );
}
