'use client'
import type { Metadata } from "next";
import "../../globals.css";
import { satoshi } from "@/config/font";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { useEffect, useState } from "react";
import { Icon } from "@iconify/react/dist/iconify.js";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function InsightLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
    
  return (
   <div className={`${satoshi.variable} antialiased`}>
      <div className="relative flex flex-col h-screen">
        <main className="flex-grow bg-[#0D102F]">
          {/* Your custom header for insights */}
        
          {children}
          {/* Your custom footer for insights */}
    
        </main>
      </div>
    </div>

  );
}
